"""Dataset locations, resolved in one place.

Resolution order for every dataset, highest priority first:

  1. the command-line flag on the script you are running (``--nsynth-root``)
  2. the environment variable (``DRONE_NSYNTH``)
  3. the default below, which is where the data sits on the cluster host the
     project was built on

The defaults are recorded so the pipeline is reproducible on that host without
arguments. They will not exist on your machine.

``data`` is the odd one out: it is where this pipeline *writes*, not a dataset
you download, so the scripts create it. The other five must already exist. Every script prints the path it
resolved and fails with the dataset name and where to obtain it, rather than a
bare FileNotFoundError.

Nothing under ``conductor/`` imports this module. That is deliberate: the
conductor must start with every dataset root missing.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

# Where the project was built. Present for reproducibility, not portability.
_CLUSTER = Path("/cs/student/msc/dsml/2023/myeung/THESIS_MYDIR/data")

DEFAULTS: dict[str, Path] = {
    "data":            _CLUSTER / "generated_audio",  # written by this pipeline
    "nsynth":          _CLUSTER / "nsynth-train", # contains examples.json, audio/
    "deam":            _CLUSTER / "deam",
    "emo_soundscapes": _CLUSTER / "emo_soundscapes",
    "essen":           _CLUSTER / "essen",        # also reachable via music21
    "echothief":       _CLUSTER / "echothief",    # impulse responses
}

ENV_VARS: dict[str, str] = {
    "data":            "DRONE_DATA",
    "nsynth":          "DRONE_NSYNTH",
    "deam":            "DRONE_DEAM",
    "emo_soundscapes": "DRONE_EMO",
    "essen":           "DRONE_ESSEN",
    "echothief":       "DRONE_ECHOTHIEF",
}

WHERE_TO_GET = {
    "nsynth":          "https://magenta.tensorflow.org/datasets/nsynth  (nsynth-train.jsonwav)",
    "deam":            "https://cvml.unige.ch/databases/DEAM/",
    "emo_soundscapes": "https://metacreation.net/emo-soundscapes/",
    "essen":           "http://www.esac-data.org/  (or music21.corpus)",
    "echothief":       "http://www.echothief.com/",
    "data":            "generated by this pipeline; see the run order in each README",
}

# Artefacts small enough to travel with the code live beside it, not in a
# dataset root. REPO_DATA is <code>/models/<section>/weights by convention;
# scripts pass their own.
CODE_ROOT = Path(__file__).resolve().parent.parent


def resolve(name: str, override: str | None = None) -> Path:
    """Return the root for ``name``: flag, then environment, then default."""
    if name not in DEFAULTS:
        raise KeyError(f"unknown dataset {name!r}; known: {sorted(DEFAULTS)}")
    if override:
        return Path(override).expanduser()
    env = os.environ.get(ENV_VARS[name])
    if env:
        return Path(env).expanduser()
    return DEFAULTS[name]


def require(name: str, override: str | None = None) -> Path:
    """Resolve and check. Fails with the dataset name and where to get it."""
    p = resolve(name, override)
    if not p.exists():
        raise SystemExit(
            f"\n{name} dataset not found at:\n    {p}\n\n"
            f"Point at it with --{name.replace('_', '-')}-root, or set "
            f"${ENV_VARS[name]}.\nObtain it from: {WHERE_TO_GET.get(name, 'see the report')}\n"
        )
    return p


def add_arg(parser: argparse.ArgumentParser, *names: str) -> None:
    """Add ``--<name>-root`` for each dataset, with the default in the help."""
    for n in names:
        parser.add_argument(
            f"--{n.replace('_', '-')}-root", dest=f"{n}_root", default=None,
            metavar="DIR",
            help=f"{n} dataset root (env ${ENV_VARS[n]}; default {DEFAULTS[n]})")
